import type { Product } from "./types"

// Mock products for development
export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Áo Sơ Mi Trắng Classic",
    description: "Áo sơ mi trắng cao cấp, chất liệu cotton 100%, thiết kế thanh lịch phù hợp cho mọi dịp.",
    price: 450000,
    category: "Áo Sơ Mi",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Xanh Nhạt"],
    images: ["/white-dress-shirt.jpg"],
    stock: 50,
    featured: true,
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "Quần Tây Đen Slim Fit",
    description: "Quần tây đen ôm vừa vặn, chất liệu vải cao cấp, form dáng hiện đại.",
    price: 550000,
    salePrice: 450000,
    category: "Quần",
    sizes: ["28", "29", "30", "31", "32"],
    colors: ["Đen", "Xám"],
    images: ["/black-dress-pants.png"],
    stock: 30,
    featured: true,
    createdAt: new Date(),
  },
  {
    id: "3",
    name: "Áo Thun Premium",
    description: "Áo thun cao cấp, chất liệu cotton mềm mại, thoáng mát.",
    price: 250000,
    category: "Áo Thun",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Đen", "Trắng", "Xám", "Navy"],
    images: ["/premium-t-shirt.png"],
    stock: 100,
    featured: false,
    createdAt: new Date(),
  },
  {
    id: "4",
    name: "Blazer Nam Sang Trọng",
    description: "Áo vest blazer cao cấp, thiết kế hiện đại, phù hợp cho công sở và sự kiện.",
    price: 1200000,
    salePrice: 950000,
    category: "Áo Vest",
    sizes: ["M", "L", "XL"],
    colors: ["Đen", "Navy", "Xám"],
    images: ["/mens-blazer-jacket.jpg"],
    stock: 20,
    featured: true,
    createdAt: new Date(),
  },
]
